Improved index fetching, supporting multiple versions
LyraSearch/plugin-docusaurus pull request #79
Opened 2023-01-16 07:48 UTC by stearm

This PR adds a method to retrieve only the Lyra index corresponding to the selected documentation version, as discussed in https://github.com/LyraSearch/plugin-docusaurus/issues/77#issuecomment-1380288513. For each documentation version, we create an index file.

Next steps: add the 'pattern' option to choose which indexes files to generate, and figure out how to add tests.

This is a step closer to #77.

2023-01-16 08:22 UTC, Eomm commented on src/client/theme/SearchBar/utils.ts
> +  return url.match(/\/(v[^/]+)/)?.[1] || 'latest'
Note that the version string is a customizable thing in docusaurus

- Jest sets it as `next` or `29.x` https://jestjs.io/
- Docusaurus sets it as `2.1.0` https://docusaurus.io/docs/2.1.0

I think a safer getter should get the string after `docs/<version>/` 

Even difficult: the latest version, by default, does not have the version as URL path:
`https://docusaurus.io/docs/configuration`

The `latest` thing is a fastify website's legacy

2023-01-16 09:12 UTC, Ceres6 reviewed
As it is now it only indexes docs. Before it also indexed blog and regular pages. We should probably index those in a separate index and have it as a second source independent of the version we're at.

I'm not sure if this can happen in sites without docs folder, but in that case there should be some way to tell apart doc folders from regular/blog ones

2023-01-16 09:12 UTC, Ceres6 commented on src/server/index.ts
> +      return [
I think this is a bit hard to follow. There should be a simpler way of getting folders of versions and the rest. In case there's not extracting it to functions which names states the purpose could make it easier to read.

2023-01-16 09:12 UTC, Ceres6 commented on src/client/theme/SearchBar/utils.ts
> +  return url.match(/\/(v[^/]+)/)?.[1] || 'latest'
Probably there is a way to get this from config (the latest/next thing, I mean). About the semantic versioning I think the previous regex that you had, adding optional "v" covered the option of `29.x`

2023-01-16 18:49 UTC, Eomm commented on src/client/theme/SearchBar/utils.ts
> +  return url.match(/\/(v[^/]+)/)?.[1] || 'latest'
I think it would work 👍🏽 

> if there's vX.X.X or X.X.X it's a "normal" version

Just to mention the `29.x` jest's version

2023-01-17 17:13 UTC, stearm commented
@Ceres6 I refactored the 'getDocVersionsFolders' function, and I believe it is now more readable. @Eomm, we now support versions without a 'v' as well as those used by Jest.

I'll start working on the blog and pages during next days.

2023-01-19 16:13 UTC, stearm commented
The last missing part is multi-locales support; the idea is to create indexes for each language. What I'm not sure about is how to understand which language the user selects, to retrieve the correct index. Reading the DOM is not a good solution imho. Any suggestion is appreciated.

2023-01-19 17:11 UTC, Eomm commented
You can read the `<html lang="fr"` attribute - it is set by docusaurus to let you know which lang is loaded

2023-01-31 10:26 UTC, Ceres6 requested changes

2023-01-31 10:26 UTC, Ceres6 commented on src/server/index.ts
> +        latest: latest.filter(
If docs exists then you don't need to do the first filter, you can directly take everything inside it, am I wrong?

2023-01-31 10:26 UTC, Ceres6 commented on src/server/index.ts
> +const getDocVersionsFolders = ({
I think this function does too many things and now we have fresh knowledge of all the possible structures but in the future, or anyone who is not us will probably have a hard time understanding what's going on. I would extract the parts of the function into other functions with explanatory names so each step is easier to follow.

2023-01-31 10:26 UTC, Ceres6 commented on src/server/index.ts
> +    [`${`${outDir}/${blogPath}`}/**/*.html`],
Why nesting template strings?
```ts
[`${outDir}/${blogPath}/**/*.html`]

2023-01-31 10:26 UTC, Ceres6 commented on src/server/index.ts
> +    )?.options.routeBasePath || '') as string
as per [docusaurus blog documentation](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog) the default path is `blog` (maybe it always have a value and we are just testing for the existence of the plugin).
Also here we are looking for file path so we should probably be using `path` instead of `routeBasePath` which is used for urls (maybe I'm wrong and docusaurus in the build transforms the `path` directory into the `routeBasePath` directory).

Probably we should follow the same approach with docs.

2023-02-01 20:46 UTC, frsgrn commented
Supporting search with multi-instance docs (using multiple docs plugins) would be great, really hoping that this gets merged.

2023-03-09 16:00 UTC, closed without merging